import type { PortraitDomain, SensitiveDataLevel } from "./data-contract";

export type MetricAvailability = "ready" | "requires-source-fields" | "requires-workflow-source" | "not-in-scope";

export interface PortraitMetricDefinition {
  key: string;
  domain: PortraitDomain;
  label: string;
  availability: MetricAvailability;
  calculation: string;
  requiredFields: string[];
  comparability: "district-comparable" | "within-school-trend-only" | "not-comparable";
  sensitivity: SensitiveDataLevel;
  notes?: string;
}

/**
 * 页面允许展示的指标及其计算前提。
 *
 * 该清单是产品口径，不是 UI 配置：新卡片或排名进入页面前必须在这里
 * 明确其原始字段、可比范围与敏感级别。
 */
export const portraitMetricRegistry: readonly PortraitMetricDefinition[] = [
  {
    key: "enrolled-student-count",
    domain: "profile",
    label: "在籍学生",
    availability: "ready",
    calculation: "统计日内处于有效学籍的去重学生数。",
    requiredFields: ["studentId", "schoolId", "educationStage", "grade", "enrollmentStatus"],
    comparability: "district-comparable",
    sensitivity: "normal",
  },
  {
    key: "five-education-goal-completion-rate",
    domain: "five-education",
    label: "成长目标完成率",
    availability: "ready",
    calculation: "有效学生记录的已获学分总和 ÷ 目标学分总和。",
    requiredFields: ["targetCredits", "earnedCredits", "academicYear", "term", "status"],
    comparability: "district-comparable",
    sensitivity: "normal",
  },
  {
    key: "five-education-evaluation-coverage-rate",
    domain: "five-education",
    label: "成长评价覆盖率",
    availability: "ready",
    calculation: "至少有一条有效成长评价的学生数 ÷ 有效在籍学生数。",
    requiredFields: ["evaluationFormVersion", "dimension", "secondaryIndicator", "item", "level"],
    comparability: "district-comparable",
    sensitivity: "normal",
  },
  {
    key: "five-education-evaluated-student-count",
    domain: "five-education",
    label: "参评学生数",
    availability: "ready",
    calculation: "当前筛选范围内至少有一条有效成长评价记录的去重学生数。",
    requiredFields: ["studentId", "evaluationFormVersion", "status"],
    comparability: "district-comparable",
    sensitivity: "normal",
  },
  {
    key: "five-education-evaluation-record-count",
    domain: "five-education",
    label: "评价结果数",
    availability: "ready",
    calculation: "当前筛选范围内状态有效且能关联评价表版本的评价项结果记录数。",
    requiredFields: ["sourceRecordId", "evaluationFormVersion", "dimension", "secondaryIndicator", "item", "level", "status"],
    comparability: "district-comparable",
    sensitivity: "normal",
  },
  {
    key: "five-education-evaluation-form-version-count",
    domain: "five-education",
    label: "使用评价表",
    availability: "ready",
    calculation: "当前筛选范围内有效评价记录关联的去重评价表版本数；跨学段时允许存在多个版本。",
    requiredFields: ["evaluationFormVersion"],
    comparability: "not-comparable",
    sensitivity: "normal",
  },
  {
    key: "academic-relative-position-change",
    domain: "academic",
    label: "校内同年级相对位置变化",
    availability: "ready",
    calculation: "同一学生、同一学科、可比考试的相对位置变化；相对位置不是跨校绝对学业水平。",
    requiredFields: ["examId", "subject", "rank", "comparableStudentCount", "comparableScope"],
    comparability: "within-school-trend-only",
    sensitivity: "sensitive",
  },
  {
    key: "academic-exam-coverage-rate",
    domain: "academic",
    label: "有效考试覆盖率",
    availability: "ready",
    calculation: "至少有一条有效考试记录的学生数 ÷ 有效在籍学生数。",
    requiredFields: ["examId", "score", "fullScore", "examAt"],
    comparability: "within-school-trend-only",
    sensitivity: "sensitive",
  },
  {
    key: "academic-unified-exam-record-coverage-rate",
    domain: "academic",
    label: "统考成绩记录覆盖率",
    availability: "ready",
    calculation: "至少有一条有效区级统考成绩记录的学生数 ÷ 有效在籍学生数；它反映数据接入覆盖，不等同于统考报名率或实考率。",
    requiredFields: ["examId", "examType", "administrationScope", "assessmentProgramId", "paperVersion", "assessmentGrade", "subject", "score", "fullScore", "examAt"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "统考得分率只在同一考试批次、学科、年级和试卷版本内发布。",
  },
  {
    key: "academic-unified-exam-average-score-rate",
    domain: "academic",
    label: "区域平均得分率",
    availability: "ready",
    calculation: "同一统考批次、学段、年级、学科和试卷版本内的成绩总和 ÷ 满分总和。",
    requiredFields: ["examId", "assessmentProgramId", "paperVersion", "assessmentGrade", "subject", "score", "fullScore"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "academic-unified-exam-standard-score",
    domain: "academic",
    label: "学校标准分",
    availability: "ready",
    calculation: "同一统考可比群体内，以区域学生得分率均值和标准差计算学校平均 T 分数：50 + 10 × (学校均值 - 区域均值) ÷ 区域标准差。",
    requiredFields: ["examId", "assessmentGrade", "subject", "schoolId", "score", "fullScore"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "区域自身的标准分基准恒为 50；只有学校、片区等子群体标准分具有比较意义。",
  },
  {
    key: "academic-unified-exam-excellent-rate",
    domain: "academic",
    label: "优秀率",
    availability: "ready",
    calculation: "同一统考可比群体内达到分数段政策优秀阈值的学生数 ÷ 有效成绩学生数。",
    requiredFields: ["score", "fullScore", "scoreBandPolicyVersion"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "academic-unified-exam-good-or-above-rate",
    domain: "academic",
    label: "良好及以上率",
    availability: "ready",
    calculation: "同一统考可比群体内达到分数段政策良好阈值的学生数 ÷ 有效成绩学生数。",
    requiredFields: ["score", "fullScore", "scoreBandPolicyVersion"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "academic-unified-exam-pass-rate",
    domain: "academic",
    label: "及格率",
    availability: "ready",
    calculation: "同一统考可比群体内达到分数段政策及格阈值的学生数 ÷ 有效成绩学生数。",
    requiredFields: ["score", "fullScore", "scoreBandPolicyVersion"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "academic-unified-exam-low-score-rate",
    domain: "academic",
    label: "低分率",
    availability: "ready",
    calculation: "同一统考可比群体内低于分数段政策及格阈值的学生数 ÷ 有效成绩学生数。",
    requiredFields: ["score", "fullScore", "scoreBandPolicyVersion"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "academic-unified-exam-score-band-distribution",
    domain: "academic",
    label: "分数段学生分布",
    availability: "ready",
    calculation: "按版本化优秀、良好、及格和低分阈值互斥分组，分别统计人数及占有效成绩学生数的比例。",
    requiredFields: ["score", "fullScore", "scoreBandPolicyVersion"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "academic-unified-exam-score-rate-trend",
    domain: "academic",
    label: "统考得分率变化",
    availability: "ready",
    calculation: "同一考试计划、学段、年级和学科内，按考试时间排列各统考批次得分率及相邻变化。",
    requiredFields: ["assessmentProgramId", "assessmentGrade", "subject", "examAt", "score", "fullScore"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "这是描述性变化，不等同于控制起点、试卷难度后的学业增值。",
  },
  {
    key: "academic-knowledge-module-mastery",
    domain: "academic",
    label: "知识模块掌握情况",
    availability: "requires-source-fields",
    calculation: "按题目—知识模块映射汇总模块实得分 ÷ 模块满分，并保持试卷蓝图版本一致。",
    requiredFields: ["questionId", "knowledgeModuleId", "questionScore", "questionFullScore", "assessmentBlueprintVersion"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "academic-value-added",
    domain: "academic",
    label: "学业增值水平",
    availability: "requires-source-fields",
    calculation: "基于稳定匹配学生群体、可比起点和经审定模型估计实际结果相对预期结果的变化。",
    requiredFields: ["baselineAssessmentId", "outcomeAssessmentId", "matchedCohortId", "valueAddedModelVersion"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "academic-score-stability",
    domain: "academic",
    label: "成绩稳定性",
    availability: "requires-source-fields",
    calculation: "同一学生群体至少三个可比批次的标准化成绩波动，经群体聚合后发布。",
    requiredFields: ["comparableAssessmentSequence", "studentId", "standardizedScore", "stabilityRuleVersion"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "honor-student-coverage-rate",
    domain: "honor",
    label: "荣誉覆盖率",
    availability: "ready",
    calculation: "至少获得一项去重荣誉的学生数 ÷ 有效在籍学生数。",
    requiredFields: ["kind", "name", "receivedAt", "sourceRecordId"],
    comparability: "district-comparable",
    sensitivity: "normal",
    notes: "仅描述结果分布；没有参与机会分母时不评价机会公平性。",
  },
  {
    key: "honor-per-100-students",
    domain: "honor",
    label: "每百名学生荣誉数",
    availability: "ready",
    calculation: "去重荣誉记录数 ÷ 有效在籍学生数 × 100。",
    requiredFields: ["sourceRecordId", "studentId", "receivedAt"],
    comparability: "district-comparable",
    sensitivity: "normal",
  },
  {
    key: "honor-national-count",
    domain: "honor",
    label: "国家级获奖数",
    availability: "ready",
    calculation: "当前筛选范围内奖项级别编码为国家级的有效荣誉记录数。",
    requiredFields: ["sourceRecordId", "level", "receivedAt", "status"],
    comparability: "not-comparable",
    sensitivity: "normal",
  },
  {
    key: "honor-provincial-count",
    domain: "honor",
    label: "省级获奖数",
    availability: "ready",
    calculation: "当前筛选范围内奖项级别编码为省级的有效荣誉记录数。",
    requiredFields: ["sourceRecordId", "level", "receivedAt", "status"],
    comparability: "not-comparable",
    sensitivity: "normal",
  },
  {
    key: "honor-city-count",
    domain: "honor",
    label: "市级获奖数",
    availability: "ready",
    calculation: "当前筛选范围内奖项级别编码为市级的有效荣誉记录数。",
    requiredFields: ["sourceRecordId", "level", "receivedAt", "status"],
    comparability: "not-comparable",
    sensitivity: "normal",
  },
  {
    key: "fitness-standard-pass-rate",
    domain: "sports-health",
    label: "体质测试达标率",
    availability: "ready",
    calculation: "按同一国家标准版本、适用人群和测试项目统计达标学生数 ÷ 有效测试学生数。",
    requiredFields: ["metric", "value", "standardStatus", "standardVersion", "testedAt", "sex", "educationStage"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "只在同一标准版本和适用项目范围内比较；没有有效体测记录的学生不进入达标率分母。",
  },
  {
    key: "fitness-test-record-coverage-rate",
    domain: "sports-health",
    label: "体测覆盖率",
    availability: "ready",
    calculation: "至少有一条适用且有效体测记录的学生数 ÷ 有效在籍学生数。",
    requiredFields: ["testBatchId", "metric", "standardStatus", "standardVersion", "testedAt"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "这是数据覆盖指标，不等同于体质达标率。",
  },
  {
    key: "ai-exercise-participation-rate",
    domain: "sports-health",
    label: "AI 体锻参与率",
    availability: "ready",
    calculation: "统计周期内至少一次有效体锻的学生数 ÷ 有效在籍学生数。",
    requiredFields: ["exerciseType", "sessionCount", "completedAt", "isVerified"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "ai-exercise-sessions-per-participant",
    domain: "sports-health",
    label: "AI 体锻参与学生人均次数",
    availability: "ready",
    calculation: "有效体锻记录的 sessionCount 总和 ÷ 有效参与学生数。",
    requiredFields: ["exerciseType", "sessionCount", "completedAt", "isVerified"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "sports-goal-completion-rate",
    domain: "sports-health",
    label: "运动目标完成率",
    availability: "ready",
    calculation: "体育成长目标已获学分总和 ÷ 体育成长目标学分总和。",
    requiredFields: ["goalCategory", "targetCredits", "earnedCredits"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "反映已登记体育成长目标的完成情况，不等同于体质达标率。",
  },
  {
    key: "sunshine-run-participation-rate",
    domain: "sports-health",
    label: "阳光长跑参与率",
    availability: "ready",
    calculation: "统计周期内至少一条有效跑步记录的学生数 ÷ 有效在籍学生数。",
    requiredFields: ["distanceKilometers", "durationSeconds", "completedAt", "isValidRun"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "sunshine-run-total-distance",
    domain: "sports-health",
    label: "阳光长跑累计路程",
    availability: "ready",
    calculation: "统计周期内全部有效跑步记录的 distanceKilometers 求和。",
    requiredFields: ["distanceKilometers", "completedAt", "isValidRun"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "sunshine-run-distance-per-participant",
    domain: "sports-health",
    label: "阳光长跑参与学生人均里程",
    availability: "ready",
    calculation: "有效跑步里程总和 ÷ 有效参与学生数。",
    requiredFields: ["distanceKilometers", "durationSeconds", "completedAt", "isValidRun"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "sunshine-run-session-count",
    domain: "sports-health",
    label: "阳光长跑累计人次",
    availability: "ready",
    calculation: "统计周期内有效阳光长跑记录数。",
    requiredFields: ["completedAt", "isValidRun"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "sunshine-run-duration-per-participant",
    domain: "sports-health",
    label: "阳光长跑参与学生人均时长",
    availability: "ready",
    calculation: "全部有效跑步时长秒数 ÷ 3600 ÷ 有效参与学生数。",
    requiredFields: ["durationSeconds", "completedAt", "isValidRun"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "fitness-test-item-pass-rate",
    domain: "sports-health",
    label: "体测项目达标率",
    availability: "ready",
    calculation: "在同一标准版本下，达标、良好或优秀的有效测试记录数 ÷ 有效测试记录数。",
    requiredFields: ["metric", "standardStatus", "standardVersion", "testedAt"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "practice-participation-rate",
    domain: "practice",
    label: "实践活动参与率",
    availability: "ready",
    calculation: "至少参与一次有效实践活动的学生数 ÷ 有效在籍学生数。",
    requiredFields: ["activityId", "category", "participatedAt", "isVerified"],
    comparability: "district-comparable",
    sensitivity: "normal",
  },
  {
    key: "practice-activity-count-per-student",
    domain: "practice",
    label: "生均有效活动次数",
    availability: "ready",
    calculation: "当前筛选范围内已核验实践活动记录数 ÷ 有效在籍学生数。",
    requiredFields: ["activityId", "participatedAt", "isVerified"],
    comparability: "district-comparable",
    sensitivity: "normal",
    notes: "活动次数用于描述参与强度，不代表活动质量。",
  },
  {
    key: "practice-category-count-per-student",
    domain: "practice",
    label: "生均参与类型数",
    availability: "ready",
    calculation: "逐学生去重后的活动类型数合计 ÷ 有效在籍学生数。",
    requiredFields: ["studentId", "category", "isVerified"],
    comparability: "district-comparable",
    sensitivity: "normal",
    notes: "同一学生同一类型参加多次只计一个参与类型。",
  },
  {
    key: "practice-category-coverage-rate",
    domain: "practice",
    label: "活动类型覆盖率",
    availability: "ready",
    calculation: "当前筛选范围内至少有一条已核验记录的活动类型数 ÷ 7 个注册活动类型。",
    requiredFields: ["category", "isVerified"],
    comparability: "district-comparable",
    sensitivity: "normal",
    notes: "类型覆盖不代表各类型机会充分或参与均衡。",
  },
  ...([
    ["moral", "德育活动参与人数"],
    ["intellectual", "智育活动参与人数"],
    ["physical", "体育活动参与人数"],
    ["aesthetic", "美育活动参与人数"],
    ["labor", "劳动实践参与人数"],
    ["club", "社团活动参与人数"],
    ["volunteer", "志愿活动参与人数"],
  ] as const).map(([category, label]) => ({
    key: `practice-${category}-participant-count`,
    domain: "practice" as const,
    label,
    availability: "ready" as const,
    calculation: `当前筛选范围内至少参加一次已核验${label.replace("参与人数", "")}的去重学生数。`,
    requiredFields: ["studentId", "category", "isVerified"],
    comparability: "district-comparable" as const,
    sensitivity: "normal" as const,
    notes: "同一学生同一类型参加多次只计一人。",
  })),
  ...([
    ["moral", "德育活动参与率"],
    ["intellectual", "智育活动参与率"],
    ["physical", "体育活动参与率"],
    ["aesthetic", "美育活动参与率"],
    ["labor", "劳动实践参与率"],
    ["club", "社团活动参与率"],
    ["volunteer", "志愿活动参与率"],
  ] as const).map(([category, label]) => ({
    key: `practice-${category}-participation-rate`,
    domain: "practice" as const,
    label,
    availability: "ready" as const,
    calculation: `当前筛选范围内至少参加一次已核验${label.replace("参与率", "")}的去重学生数 ÷ 有效在籍学生数。`,
    requiredFields: ["studentId", "category", "isVerified"],
    comparability: "district-comparable" as const,
    sensitivity: "normal" as const,
    notes: "同一学生同一类型参加多次只计一人；分母保留未参加该类活动的有效在籍学生。",
  })),
  {
    key: "library-borrower-coverage-rate",
    domain: "behavior",
    label: "图书借阅覆盖率",
    availability: "ready",
    calculation: "统计周期内至少借阅一本图书的学生数 ÷ 有效在籍学生数。",
    requiredFields: ["bookId", "category", "borrowedAt"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "借阅不等于完成阅读或学习质量。",
  },
  {
    key: "library-visit-coverage-rate",
    domain: "behavior",
    label: "图书馆到馆覆盖率",
    availability: "ready",
    calculation: "统计周期内至少有一次有效到馆记录的学生数 ÷ 有效在籍学生数。",
    requiredFields: ["enteredAt", "studentId", "schoolId"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "到馆不等于借阅、阅读完成或学习质量。",
  },
  {
    key: "library-visits-per-student",
    domain: "behavior",
    label: "生均入馆次数",
    availability: "ready",
    calculation: "当前筛选学期内有效入馆记录数 ÷ 当前范围有效在籍学生数；同一学生多次入馆分别计数。",
    requiredFields: ["enteredAt", "studentId", "schoolId", "sourceRecordId"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "分母包含未到馆学生；用于降低区域规模差异，不代表阅读质量。",
  },
  {
    key: "library-dwell-hours-per-student",
    domain: "behavior",
    label: "生均泡馆时长",
    availability: "ready",
    calculation: "当前筛选学期内有效泡馆总小时数 ÷ 当前范围有效在籍学生数；总小时数由每条有效离馆时间减入馆时间后汇总。",
    requiredFields: ["enteredAt", "leftAt", "studentId", "schoolId"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "缺少离馆时间或时长非正数的记录不进入时长汇总；分母仍为全部有效在籍学生。",
  },
  {
    key: "book-borrow-volume-per-student",
    domain: "behavior",
    label: "生均借阅册数",
    availability: "ready",
    calculation: "当前筛选学期内去重后的有效图书借阅明细数 ÷ 当前范围有效在籍学生数；一条图书明细计一册。",
    requiredFields: ["bookId", "borrowedAt", "sourceRecordId"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "借阅册数不等于完成阅读册数。",
  },
  {
    key: "book-borrow-transactions-per-student",
    domain: "behavior",
    label: "生均借阅次数",
    availability: "ready",
    calculation: "当前筛选学期内按 borrowTransactionId 去重的借阅交易数 ÷ 当前范围有效在籍学生数；同一次借多册只计一次。",
    requiredFields: ["borrowTransactionId", "borrowedAt", "sourceRecordId"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "旧数据缺少借阅交易标识时以原始记录 ID 兜底，接入真实数据后应通过质量规则单独标记。",
  },
  {
    key: "library-visit-count-last-7-days",
    domain: "behavior",
    label: "近 7 天入馆次数",
    availability: "ready",
    calculation: "以当前筛选范围内图书馆与借阅来源的最新业务时间为截止日，累计最近 7 个自然日的有效入馆记录数。",
    requiredFields: ["enteredAt", "studentId", "schoolId", "sourceRecordId"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "这是区域累计次数，不是到馆人数；演示数据以数据最新日为时间锚点。",
  },
  {
    key: "library-visit-count-last-30-days",
    domain: "behavior",
    label: "近 30 天入馆次数",
    availability: "ready",
    calculation: "以当前筛选范围内图书馆与借阅来源的最新业务时间为截止日，累计最近 30 个自然日的有效入馆记录数。",
    requiredFields: ["enteredAt", "studentId", "schoolId", "sourceRecordId"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "这是区域累计次数，不是到馆人数；演示数据以数据最新日为时间锚点。",
  },
  {
    key: "book-borrow-volume-last-7-days",
    domain: "behavior",
    label: "近 7 天借阅册数",
    availability: "ready",
    calculation: "以当前筛选范围内图书馆与借阅来源的最新业务时间为截止日，累计最近 7 个自然日的有效图书借阅明细数。",
    requiredFields: ["bookId", "borrowedAt", "sourceRecordId"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "一条有效借阅明细计一册，不等于完成阅读册数。",
  },
  {
    key: "book-borrow-volume-last-30-days",
    domain: "behavior",
    label: "近 30 天借阅册数",
    availability: "ready",
    calculation: "以当前筛选范围内图书馆与借阅来源的最新业务时间为截止日，累计最近 30 个自然日的有效图书借阅明细数。",
    requiredFields: ["bookId", "borrowedAt", "sourceRecordId"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "一条有效借阅明细计一册，不等于完成阅读册数。",
  },
  {
    key: "book-borrow-transaction-count-last-7-days",
    domain: "behavior",
    label: "近 7 天借阅次数",
    availability: "ready",
    calculation: "以当前筛选范围内图书馆与借阅来源的最新业务时间为截止日，按 borrowTransactionId 去重最近 7 个自然日的借阅交易。",
    requiredFields: ["borrowTransactionId", "borrowedAt", "sourceRecordId"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "同一次借多册只计一次；缺少交易标识时以原始记录 ID 兜底。",
  },
  {
    key: "book-borrow-transaction-count-last-30-days",
    domain: "behavior",
    label: "近 30 天借阅次数",
    availability: "ready",
    calculation: "以当前筛选范围内图书馆与借阅来源的最新业务时间为截止日，按 borrowTransactionId 去重最近 30 个自然日的借阅交易。",
    requiredFields: ["borrowTransactionId", "borrowedAt", "sourceRecordId"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "同一次借多册只计一次；缺少交易标识时以原始记录 ID 兜底。",
  },
  {
    key: "attendance-event-rate",
    domain: "behavior",
    label: "考勤异常发生率",
    availability: "requires-source-fields",
    calculation: "迟到、早退、晚归等异常事件数 ÷ 应考勤人次。",
    requiredFields: ["type", "recordedAt", "scheduledAttendanceCount"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "不能只以事件次数比较不同学期或不同年级。",
  },
  {
    key: "campus-meal-coverage-rate",
    domain: "life",
    label: "校内用餐记录覆盖率",
    availability: "requires-source-fields",
    calculation: "在校供餐日有对应餐次有效记录的学生数 ÷ 有供餐资格学生数。",
    requiredFields: ["category", "consumedAt", "mealSchedule", "eligibleMealStudentCount"],
    comparability: "not-comparable",
    sensitivity: "highly-sensitive",
    notes: "没有校内交易不等于未用餐；该指标不进入成长评价。",
  },
  {
    key: "campus-consumption-record-coverage-rate",
    domain: "life",
    label: "校内消费记录覆盖率",
    availability: "requires-source-fields",
    calculation: "统计周期内至少一笔有效校内消费记录的学生数 ÷ 有效在籍学生数。",
    requiredFields: ["category", "amount", "consumedAt", "studentId"],
    comparability: "not-comparable",
    sensitivity: "highly-sensitive",
    notes: "仅用于核对接入覆盖；无校内消费记录不代表未消费或未用餐。",
  },
  {
    key: "daily-evaluation-record-coverage-rate",
    domain: "daily-evaluation",
    label: "日常评价记录覆盖率",
    availability: "ready",
    calculation: "统计周期内至少有一条有效日常评价记录的学生数 ÷ 当前范围有效在籍学生数。",
    requiredFields: ["studentId", "type", "evaluatedAt", "evaluationFormVersion"],
    comparability: "district-comparable",
    sensitivity: "sensitive",
    notes: "覆盖率只反映是否形成记录，不代表学生表现或教师评价质量。",
  },
  {
    key: "daily-evaluation-positive-rate",
    domain: "daily-evaluation",
    label: "正向评价占比",
    availability: "ready",
    calculation: "表扬记录数 ÷ 全部有效日常评价记录数。",
    requiredFields: ["type", "evaluatedAt", "evaluationFormVersion"],
    comparability: "within-school-trend-only",
    sensitivity: "sensitive",
    notes: "须同时展示评价覆盖率；不同评价频率不能直接比较。",
  },
  {
    key: "daily-evaluation-improvement-rate",
    domain: "daily-evaluation",
    label: "待改进评价占比",
    availability: "ready",
    calculation: "待改进记录数 ÷ 全部有效日常评价记录数。",
    requiredFields: ["type", "evaluatedAt", "evaluationFormVersion"],
    comparability: "within-school-trend-only",
    sensitivity: "sensitive",
    notes: "仅描述评价记录结构，不代表学生问题率；须与记录覆盖率同时展示。",
  },
  {
    key: "daily-improvement-closure-rate",
    domain: "daily-evaluation",
    label: "改进项闭环率",
    availability: "requires-workflow-source",
    calculation: "已复核关闭的改进事项数 ÷ 已创建改进事项数。",
    requiredFields: ["improvementId", "workflowStatus", "resolvedAt", "reviewedAt"],
    comparability: "not-comparable",
    sensitivity: "sensitive",
  },
  {
    key: "clinic-symptom-cluster",
    domain: "life",
    label: "校内就诊症状聚集",
    availability: "requires-source-fields",
    calculation: "在授权范围内按时间窗口、症状编码与最小样本门槛识别聚集。",
    requiredFields: ["symptomCodes", "visitedAt", "studentId", "schoolId"],
    comparability: "not-comparable",
    sensitivity: "highly-sensitive",
    notes: "仅限最小必要匿名汇总，不用于学生标签、排名或疾病诊断。",
  },
];

export const portraitMetricDefinitionByKey = new Map(
  portraitMetricRegistry.map((definition) => [definition.key, definition]),
);
